#!/bin/bash

TARGET_FILE=$1
TARGET_DIR=`dirname $TARGET_FILE`
MONO_TEXTTEMPLATING_FILE="$TARGET_DIR/Mono.TextTemplating.dll"

DEST[0]=~/.config/MonoDevelop/addins/
DEST[1]=~/githome/monodevelop/main/build/AddIns/MonoDevelop.NHibernate

for DIR in ${DEST[*]}; do
	if [ ! -d $DIR ]; then
		mkdir $DIR
	fi
	cp $TARGET_FILE $DIR
	cp $MONO_TEXTTEMPLATING_FILE $DIR
done
